name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build and Push the Docker image
      run: docker buildx build 
        --platform=linux/arm64,linux/amd64 
        --tag ${{ secrets.DOCKER_USER }}/http-proxy:$GITHUB_REF_NAME 
        --file Dockerfile 
        --push .
    - name: Docker Logout
      run: docker logout
