name: Docker Image CI

on:
  push:
    tags:
      - '*'

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_USER: go-bai
  APP_NAME: http-proxy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Docker
      run: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    - name: Set up Docker Environment
      run: docker buildx create
        --name=multi-builder
        --driver=docker-container
        --platform=linux/arm64,linux/amd64
        --use
        --bootstrap
    - name: Docker Login
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      run: |
        echo ${{ env.GHCR_TOKEN }} | docker login ${{ env.GHCR_REGISTRY }} --username ${{ env.GHCR_USER }} --password-stdin
    - name: Build and Push the Docker image
      run: docker buildx build
        --platform=linux/arm64,linux/amd64
        --tag ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_USER }}/${{ env.APP_NAME }}:$GITHUB_REF_NAME
        --file Dockerfile
        --push .
    - name: Docker Logout
      run: docker logout ${{ env.GHCR_REGISTRY }}
