name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
        GO111MODULE: on
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/http-proxy:$GITHUB_REF_NAME
    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USER }}/http-proxy:$GITHUB_REF_NAME
